### ISSUE TITLE
How to expand the input length to 2048 tokens?

### ISSUE THREAD

**Issue by michelleqyhqyh** [baoguangsheng/g-transformer#10]
![image](https://user-images.githubusercontent.com/45490378/147223608-c2fae116-3ae9-42bf-bf85-3644c166ef20.png)

I modified "--max-tokens" to 2048 in "prepare-randinit.sh" to prepare all data. Then I started to train, but there is an error about "max_positions". Do you know how to fix this problem?

Furthermore, is there anything else I should pay attention to?

Acually, I want to know when the input length is expanded to 2048 tokens, d-BLEU will be declining? Have you ever done an experiment like this？What is the current maximum input length（input tokens） given that d-BLEU is stable？

**Comment by baoguangsheng** [comment]
The parameter --max-tokens specifies the total tokens for one batch to contain. The maximum supported sequence length is specified by --max-positions which is provided by fairseq framework. There is not any limitation to the maximum input length, the only problem is the GPU memory.

**Comment by michelleqyhqyh** [comment]
> The parameter --max-tokens specifies the total tokens for one batch to contain. The maximum supported sequence length is specified by --max-positions which is provided by fairseq framework. There is not any limitation to the maximum input length, the only problem is the GPU memory.

Do you know where I should modify? Can you please give me some specific guide of codes?

**Comment by baoguangsheng** [comment]
I think you only need to add the argument --max-positions into run-xxx script to specify a longer input. For more detailed code about this argument, you could search for the name in code files.
