### ISSUE TITLE
Do you know how to add g-transformer into openNMT?

### ISSUE THREAD

**Issue by michelleqyhqyh** [baoguangsheng/g-transformer#11]

**Comment by baoguangsheng** [comment]
Can you call to fairseq code from openNMT? If you can, you should be able to call g-transformer directly.

**Comment by michelleqyhqyh** [comment]
I don't know how to call fairseq in openNMT, I found it seems there is no fairseq in openNMT. Can you please give me some points?

**Comment by baoguangsheng** [comment]
I am actually not sure about it. But you maybe could try calling fairseq package from openNMT directly.
