### ISSUE TITLE
Can you provide the version of fairseq which the code is based?

### ISSUE THREAD

**Issue by nomadlx** [baoguangsheng/g-transformer#12]
I need the exact commit id information for comparison.

**Comment by baoguangsheng** [comment]
We use the version between 0.9.0 and 1.10.0, which can be got from [snapshot](https://drive.google.com/file/d/1UJmZn9LXPvOoifVKblt0RhUFsZRusOrt/view?usp=sharing).

**Comment by baoguangsheng** [comment]
Besides, we marked the key changes of the code with comment prefix '# Guangsheng Bao',. Hope that can help.

**Comment by nomadlx** [comment]
Thanks for the snapshot you provided. In fact, I am trying to understand why ["fp16 does not support param groups."](https://github.com/baoguangsheng/g-transformer/blob/908244a3bfde37184c6dd4dbe35d58159e919d93/fairseq/trainer.py#L186) , whether it exists in the original code, or you do not provide support for this.
I found your comment while reading the code, but if you can compress the base code into a single commit, I think you modify would be easier to see.

**Comment by baoguangsheng** [comment]
That fairseq version does not support it. I tried to change the fp16 code to support param groups but it seems not that easy.

**Comment by baoguangsheng** [comment]
Compressing the base code into a single commit sounds a good practice. I would definitely like to try it next time. Thanks.
