### ISSUE TITLE
The BLEU value

### ISSUE THREAD

**Issue by thunder123321** [baoguangsheng/g-transformer#13]
May I ask whether it is tokenized BLEU or detokenized BLEU in G-transformer's paper?

**Comment by baoguangsheng** [comment]
It is detokenized BLEU, which is specified by the arguments "--tokenizer moses --remove-bpe --sacrebleu".

**Comment by thunder123321** [comment]
All right, thank you very much

**Comment by baoguangsheng** [comment]
You are welcome.
