### ISSUE TITLE
一些关于baseline的问题

### ISSUE THREAD

**Issue by kaiyuhwang** [baoguangsheng/g-transformer#2]
您好，如果我想复现您论文中的strong baseline-Transformer on sent (baseline) 上面的结果，该如何设置arch、task等fairseq-train中的参数？
此外，该baseline和SentNMT有什么区别？

**Comment by baoguangsheng** [comment]
您好，复现脚本已放到baselines文件夹中，具体设置还请查看相应得脚本。我们的基线和sent NMT都使用Transformer，具体参数会有些不同。谢谢。

**Comment by kaiyuhwang** [comment]
> 
> 
> 您好，复现脚本已放到baselines文件夹中，具体设置还请查看相应得脚本。我们的基线和sent NMT都使用Transformer，具体参数会有些不同。谢谢。

十分感谢您的回复！

**Comment by zhaoguangxiang** [comment]
请求提供doc transformer 的baseline脚本
