### ISSUE TITLE
About  the realasing of the best checkpoint 

### ISSUE THREAD

**Issue by Rooders** [baoguangsheng/g-transformer#4]
Hello, thank your contribution, which is excellent work. 
Could you send me the best checkpoint ?  I want to use it to generate some translations for analysis.
Thanks again.
E-mail: hongsonghk@gmail.com

**Comment by baoguangsheng** [comment]
Hi Rooders,
Which specific dataset and setting are you interested in? If we consider different datasets and settings, there are about 10 models, which will occupy a plenty of public storage. We do not have a plan to do so given that these models can be easily obtained using the training scripts. Thanks.
