### ISSUE TITLE
I can't use scripts for the baseline of doc transformer

### ISSUE THREAD

**Issue by KIMDOKYOUNG** [baoguangsheng/g-transformer#7]
Hi author,I can't use scripts for the baseline of doc transformer. After cloning the new fairseq and copied the baseline scripts to fairseq root folder. but fairseq/models/transformer.py does not exist in the newly downloaded fairseq folder. so I just appending the model setting to fairseq/models/transformer/transformer_legacy.py. Then I get an error. Could you please explain what I am missing or what is wrong? Thanks.

**Comment by baoguangsheng** [comment]
Hi, since the recent change to fairseq repo, the version is different from mine now. Please use fairseq (v0.9.0) at https://github.com/pytorch/fairseq/releases/tag/v0.9.0 for the baseline. Thanks.

**Comment by KIMDOKYOUNG** [comment]
Hi author, thanks for answering my questions. The baseline script has the parameter patience, which is not present in version 0.9.0, giving an error. So, when using v0.9.0, I deleted the patience parameter(patience 10) from the script(run_sent.sh) and trained it. When I googled, the parameter was a parameter for early stopping, so the number of epochs is 3 times higher than when learning g-transformer. I couldn't give the same parameters, but can the trained model be considered a baseline?

**Comment by baoguangsheng** [comment]
It seems that I was using an intermediate version between v0.9.0 and v0.10.0. Anyway, I pack my local version of fairseq and store at   https://drive.google.com/file/d/1UJmZn9LXPvOoifVKblt0RhUFsZRusOrt/view?usp=sharing. Hope that it can help. Thanks.
