### ISSUE TITLE
How to calculate s-BLEU and d-BLEU with generated test results? 

### ISSUE THREAD

**Issue by michelleqyhqyh** [baoguangsheng/g-transformer#9]

**Comment by baoguangsheng** [comment]
The s-BLEU is calcuated per sentence, while the d-BLEU is per document. The detailed algorithm can be found in fairseq_cli/generate.py where the scorer is for s-BLEU and scorer_doc is for d-BLEU.

**Comment by michelleqyhqyh** [comment]
> The s-BLEU is calcuated per sentence, while the d-BLEU is per document. The detailed algorithm can be found in fairseq_cli/generate.py where the scorer is for s-BLEU and scorer_doc is for d-BLEU.

Thank you very much!
